name = "PauliStrings"
uuid = "f07625cc-80e4-4099-a362-36a3484d9bcc"
authors = ["Nicolas Loizeau <nicolas.loizeau@nbi.ku.dk> and contributors"]
version = "1.9.1"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
MathLink = "18c93696-a329-5786-9845-8443133fa0b4"

[extensions]
SymbolicsPauliStringsExt = "Symbolics"
MathLinkPauliStringsExt = "MathLink"



[compat]
BitIntegers = "0.3.6"
Combinatorics = "1.0.3"
Dictionaries = "0.4"
ProgressBars = "1.5"
SparseArrays = "1.6.0"
Symbolics = "6.57.0"
MathLink = "0.6.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
MathLink = "18c93696-a329-5786-9845-8443133fa0b4"

[targets]
test = ["Test"]
