name = "PauliStrings"
uuid = "f07625cc-80e4-4099-a362-36a3484d9bcc"
authors = ["Nicolas Loizeau <nicolas.loizeau@nbi.ku.dk> and contributors"]
version = "1.5.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Dictionaries = "0.4"
Documenter = "1.6"
ProgressBars = "1.5"
SparseArrays = "1.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
